// Copyright (c) 2025. Tony Robalik.
// SPDX-License-Identifier: Apache-2.0
@file:Suppress("UnstableApiUsage")

package com.autonomousapps.tasks

import com.autonomousapps.TASK_GROUP_DEP
import com.autonomousapps.internal.AbiExclusions
import com.autonomousapps.model.internal.Capability
import org.gradle.api.file.ConfigurableFileCollection
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.Property
import org.gradle.api.provider.ProviderFactory
import org.gradle.api.tasks.*
import org.gradle.workers.WorkAction
import org.gradle.workers.WorkParameters
import org.gradle.workers.WorkerExecutor
import javax.inject.Inject

/**
 * Analyzes internal access patterns between Gradle modules.
 * This task detects when one module accesses internal implementation details of another module,
 * which can violate module boundaries and create tight coupling.
 */
@CacheableTask
public abstract class InternalAccessAnalysisTask @Inject constructor(
  private val workerExecutor: WorkerExecutor,
  private val providers: ProviderFactory,
) : AndroidClassesTask() {

  init {
    group = TASK_GROUP_DEP
    description = "Analyzes internal access patterns between modules"
  }

  /** Class files generated by any JVM source (Java, Kotlin, Groovy, etc.). May be empty. */
  @get:Classpath
  @get:InputFiles
  public abstract val classes: ConfigurableFileCollection

  /** ABI artifacts from all other projects in the build for cross-module analysis */
  @get:Classpath
  @get:InputFiles
  public abstract val allProjectAbis: ConfigurableFileCollection

  /** The current project path for identification */
  @get:Input
  public abstract val projectPath: Property<String>

  /** All project paths in the build for mapping */
  @get:Input
  public abstract val allProjectPaths: Property<String>

  @get:Optional
  @get:Input
  public abstract val exclusions: Property<String>

  @get:OutputFile
  public abstract val output: RegularFileProperty

  @TaskAction
  public fun action() {
    // Simple implementation for now - just create an output file
    val outputFile = output.get().asFile
    outputFile.parentFile.mkdirs()

    val currentProjectPath = projectPath.get()
    val result = "Internal access analysis for $currentProjectPath: Analysis complete"

    outputFile.writeText(result)
  }
}